local faq = {}
faq[1] = {
    ["title"] = "Häufige Fragen: Spiel",
    ["describe"] = "1.F: Wie kann ich das Spiel fortsetzen, nachdem ich mein Gerät gewechselt habe?|A: Nachdem Sie das Spiel heruntergeladen und geöffnet haben, müssen Sie in der linken oberen Ecke des Anmeldebildschirms auf das kleine Männchen klicken, Ihren Kontonamen sowie Ihr Passwort eingeben und dann das Spiel starten.|2.F: Kann ich meinen Kontonamen in Erfahrung bringen, wenn ich diesen vergessen habe?|A: Nein. Bitte vergessen Sie Ihren Kontonamen und Ihr Passwort nicht.|3.F: Was sollte ich tun, wenn mein Konto gehackt und mein Passwort geändert wurde?|A: Wenn Ihr Kontopasswort geändert wurde, dann setzen Sie sich bitte umgehend mit unserem Kundendienst in Verbindung.|4.F: Was sollte ich tun, wenn eine Netzwerk-Zeitüberschreitung auftritt und ich mich nicht anmelden kann?|A: Wenn Sie sich nicht anmelden können, dann versuchen Sie bitte erneut, eine Verbindung aufzubauen, oder erzwingen Sie das Beenden des Spiels und starten Sie es erneut. |5.F: Was sollte ich tun, wenn das Spiel fortlaufend aktualisiert wird (Wird aktualisiert…) und ich mich nicht anmelden kann.|A: Erzwingen Sie bitte das Beenden des Spiels und starten Sie es neu oder ändern Sie Ihre Netzwerkverbindung und versuchen sie es erneut. Wenn dies nicht hilft, dann setzen Sie sich bitte mit unserem Kundendienst in Verbindung.|6.F: Was sollte ich tun, wenn ich Daten oder meinen Kontonamen verloren habe?|A: Wenn Sie Daten verloren haben, dann überprüfen Sie bitte zunächst, ob Ihr Anmeldeserver korrekt ist, da die Daten auf den Servern unterschiedlich sind und untereinander nicht geteilt werden. Falls dies nicht hilft, dann setzen Sie sich bitte mit unserem Kundendienst in Verbindung. Bitte geben Sie dabei Ihre Spiel-ID und die E-Mail-Adresse, mit der Sie sich registriert haben an. |7.F: Was sollte ich tun, wenn beim Spielen ständig Verbindungsverluste auftreten?|A: Bitte überprüfen Sie zunächst den Status Ihres Netzwerks und versuchen Sie es bitte erneut, nachdem Sie die Verbindung zu dem Netzwerk aktualisiert haben. Wenn dies nicht hilft, dann setzen Sie sich bitte mit unserem Kundendienst in Verbindung.|8.F: Was sollte ich tun, wenn mein Spiel ständig abstürzt?|A: Bitte erzwingen Sie zunächst das Beenden aller Anwendungen auf Ihrem Gerät und starten Sie dann das Spiel neu. Falls das Problem weiterhin besteht, dann starten Sie Ihr Gerät neu und versuchen Sie es erneut. Wenn dies nicht hilft, dann setzen Sie sich bitte mit unserem Kundendienst unter Angabe Ihrer Geräte-ID in Verbindung.|9.F: Was sollte ich tun, wenn ich bemerke, dass ein Spieler regelwidrig handelt?|A: Unser Ziel ist es, ein faires Spielerlebnis zu gewährleisten, daher tolerieren wir es nicht, wenn Spieler Bugs ausnutzen, um sich Vorteile zu verschaffen. Wenn Sie ein solches Verhalten bemerken, dann berichten Sie uns bitte in Ihrem Feedback davon, und wir werden Maßnahmen gegen den betreffenden Spieler einleiten.",
}
faq[2] = {
    ["title"] = "Häufige Fragen: Sozial",
    ["describe"] = "1.F: Wie kann ich Spam-Nachrichten anderer Spieler in Chaträumen blockieren?|A: Tippen Sie dazu auf das Profilbild des entsprechenden Spielers im Chatraum und tippen Sie dann auf 'Blockieren'.|2.F: Was sollte ich tun, wenn ein Spieler im Chatraum Werbung verbreitet oder Nachrichten mit betrügerischer Absicht versendet?|A: Teilen Sie uns dies als Feedback (links auf der Hauptseite) mit und geben Sie dabei die Konto-ID des betreffenden Spielers an. Außerdem können Sie uns auch Screenshots mit Beweisen, der ID des Spielers usw. per E-Mail zusenden.|3.F: Wie kann ich im Spiel Freunde hinzufügen?|A: Klicken Sie dazu auf das Profilbild des entsprechenden Spielers im Chatraum und senden ihm eine Freundschaftsanfrage zu. In der Freundschaftsanfrage können Sie außerdem auch eine Spieler-ID eingeben oder empfohlenen Freunden eine Anfrage zusenden.|4.F: Wie können Freunde im Spiel zusammenarbeiten?|A: Freunde können sich gegenseitig dabei helfen, Freundes-Bosse zu töten, sie können sich gegenseitig Herzen schenken, die für eine Herzensbeschwörung verwendet werden, und sie können sich E-Mails zusenden, um so in Kontakt zu treten.|5.F: Wie kann ich einer Gilde beitreten?|A: Klicken Sie dazu auf der Hauptseite auf 'Gilde', wählen Sie eine vorgeschlagene Gilde aus und senden Sie ihr eine Anfrage zu, oder geben Sie eine Gilden-ID ein, um eine Gilde zu finden und ihr eine Anfrage zuzusenden. Sie können auch Ihre eigene Gilde gründen und andere Spieler einladen, ihr beizutreten.|6.F: Was bringt mir der Beitritt zu einer Gilde?|A: Nachdem Sie einer Gilde beigetreten sind, können Sie über das Melden das Level der Gilde erhöhen und Gildenmünzen erhalten. Ferner können Sie auch in der Mühle und in Gildenverliesen Gildenmünzen und Gold erhalten. Zudem können Sie sich für den wöchentlichen Gildenkrieg anmelden und dabei sehr viele Gildenmünzen und andere Belohnungen erbeuten.|7.F: Welche Auswirkungen hat ein Gildenwechsel?|A: Wenn Sie sich für den wöchentlichen Gildenkrieg angemeldet haben, dann können Sie nach einem Wechsel nicht länger an dem Gildenkrieg der aktuellen Woche teilnehmen und auch keine Belohnungen dafür erhalten.|8.F: Welchen Nutzen haben Gildenmünzen?|A: Mit Gildenmünzen können Sie im Gildenladen Gegenstände erwerben. Zudem können Sie sie in Gildentechnologie investieren und diese so steigern.|9.F: Welchen Nutzen hat es, Gildentechnologie zu steigern?|A: Wenn Sie die Gildentechnologie der fünf verschiedenen Spezialisierungen erhöhen, dann werden die Eigenschaften Ihrer Helden mit den jeweiligen Spezialisierungen ebenfalls erhöht.",
}
faq[3] = {
    ["title"] = "Häufige Fragen: Aufladen",
    ["describe"] = "1.F: Wie kann ich zu einem VIP-Spieler werden?|A: Wenn Sie eine bestimmte Menge an Diamanten kaufen, dann können Sie zu einem VIP-Spieler werden. Je mehr Diamanten Sie kaufen, desto höher wird Ihr VIP-Level sein und Sie werden noch mehr Privilegien genießen.|2.F: Welche Belohnung erhalte ich beim ersten Aufladen?|A: Beim ersten Aufladen erhalten Sie die doppelte Menge an Diamanten als Belohnung. Dies ist jeweils nur einmal für jeden Aufladegrad möglich. Spezielle Artikel (z.B. Monatskarten) sind hiervon ausgenommen.|3.F: Was sollte ich tun, wenn ich beim Aufladen bereits bezahlt habe, aber der Gegenstand nicht meinem Konto zugewiesen wird?|A: Versuchen Sie bitte zunächst das Spiel neu zu starten. Wenn dies auch nach mehrmaligen Versuchen nicht zum Erfolg führt, dann setzen Sie sich bitte mit unserem Kundendienst in Verbindung.|4.F: Warum kann sich die abgezogene Goldsumme nach einem erfolgreichen Kauf ändern?|A: Die aufgeladene/abgezogene Goldsumme ist von dem Wechselkurs der Währung Ihres jeweiligen Landes abhängig. Wenn der Wechselkurs schwankt, dann wird sich auch die Goldsumme ändern.",
}
faq[4] = {
    ["title"] = "Kontakt",
    ["describe"] = "Wenn Sie im Spiel auf ein Problem stoßen oder uns Ihre Verbesserungsvorschläge zusenden wollen, dann können Sie uns dies über Ihr Feedback oder per E-Mail tun. Unsere E-Mail-Adresse lautet: idleheroes.feedback@gmail.com.",
}
return faq