-- const values

-- value: "LT"--洛汀合作包; "IAS"--国内安卓自己包; nil--正常包
APP_CHANNEL = nil

-- 测试入口: true 打开，false关闭
TEST_ENTRY_ENABLE = false

-- 建筑入口禁止开关: true打开校验，false关闭校验
BUILD_ENTRIES_ENABLE = true

-- 新手引导
TUTORIAL_ENABLE = true

-- 网络超时秒数
NET_TIMEOUT = 90

-- touch attenuation coeffcient
ATTENUATION_COEFFCIENT = 3

-- url in all kinds of store
URL_GOOGLE_PLAY_ANDROID = "https://www.reddit.com/r/IdleHeroesPS"
URL_GOOGLE_PLAY_WEB = "https://www.reddit.com/r/IdleHeroesPS"
URL_APP_STORE_IOS       = "https://itunes.apple.com/us/app/idle-heroes/id1153461915"

if APP_CHANNEL and APP_CHANNEL == "LT" then
    URL_APP_STORE_IOS = "https://itunes.apple.com/us/app/fang-zhi-qi-bing-idel-heroes/id1156341344"
end

-- url of facebook profile
URL_FACEBOOK_ANDROID = "fb://page/1717588861824432"
URL_FACEBOOK_IOS     = "fb://profile/1717588861824432"
URL_FACEBOOK_WEB     = "https://www.facebook.com/IdleHeroes"

URL_TWITTER_WEB      = "https://twitter.com/IdleHeroes"
URL_TWITTER_WEB_JP   = "https://twitter.com/IdleHeroesJP"
URL_WEIBO_WEB        = "http://weibo.com/idleheroes"

-- 特殊tag used by CCNode:setTag(tag)
TAG_WAIT_NET           = 1000001
TAG_RECONNECT_DIALOG   = 1000002
TAG_RED_DOT            = 1000003
TAG_LEVEL_UP           = 1000004
TAG_UNLOCK_FUNC        = 1000005
TAG_RESUME_BTN         = 1000006

-- shader
SHADER_GRAY         = 1
SHADER_HIGHLIGHT    = 2 
SHADER_MENUITEM     = 3 
SHADER_ICE          = 4 
SHADER_INJURED      = 5 
SHADER_DARK         = 6 
SHADER_SOFT_LIGHT_NORMAL = 7
SHADER_SOFT_LIGHT_DIFFICULT = 7+8        -- 与shader里面据点对应
SHADER_SOFT_LIGHT_DUNGEON = 7+8+9       -- 与shader里面据点对应
SHADER_SOFT_LIGHT_NIGHTMARE = 7+8+9       -- 与shader里面据点对应
SHADER_SOFT_LIGHT_DREAM = 7+8+9       -- 与shader里面据点对应


-- 弹窗黑色背景的透明度
POPUP_DARK_OPACITY = 255 * 0.8

-- 阵营
GROUP_1      = 1
GROUP_2      = 2
GROUP_3      = 3
GROUP_4      = 4
GROUP_5      = 5
GROUP_6      = 6

-- 品质
QUALITY_1    = 1
QUALITY_2    = 2
QUALITY_3    = 3
QUALITY_4    = 4
QUALITY_5    = 5
QUALITY_6    = 6
QUALITY_7    = 7

-- 单位类型
UNIT_KIND_DAMAGE     = 1
UNIT_KIND_DEFENSE    = 2
UNIT_KIND_SUPPORT    = 3
UNIT_KIND_CONTROL    = 4
UNIT_KIND_EXP_FOOD   = 5

-- 水晶在equip表中对应的pos
EQUIP_POS_JADE = 5  

-- 特殊物品 id
ITEM_ID_COIN         = 1
ITEM_ID_GEM          = 2
ITEM_ID_PLAYER_EXP   = 3
ITEM_ID_GUILD_COIN   = 4
ITEM_ID_GUILD_EXP    = 5
ITEM_ID_LUCKY_COIN   = 6
ITEM_ID_RUNE_COIN    = 7
ITEM_ID_VIP_EXP      = 9
ITEM_ID_HERO_EXP     = 10
ITEM_ID_EVOLVE_EXP   = 11
ITEM_ID_LOVE         = 12
ITEM_ID_ENERGY       = 13
ITEM_ID_TRIAL_TL     = 14
ITEM_ID_CRYSTAL_PIECE      = 15
ITEM_ID_BRAVE        = 16
ITEM_ID_ARENA_SHOP        = 17
ITEM_ID_BREAD         = 19
ITEM_ID_SP_REPLACE   = 20
ITEM_ID_SP_SUMMON    = 21
ITEM_ID_SP_FIGHT     = 22
ITEM_ID_SP_FIGHT2     = 30
ITEM_ID_SP_WINNER_HEAD     = 25
ITEM_ID_SP_LOVER_HEAD     = 32
ITEM_ID_SP_F3V3_HEAD_1     = 33
ITEM_ID_SP_F3V3_HEAD_2     = 34
ITEM_ID_SP_F3V3_HEAD_3     = 35
ITEM_ID_SP_F3V3_HEAD_4     = 36
ITEM_ID_SP_F3V3_HEAD_5     = 37
ITEM_ID_SP_WARM     = 38
ITEM_ID_SP_FIGHT3     = 39
ITEM_ID_PET_DEVIL      = 40 --恶魔石
ITEM_ID_PET_CHAOS      = 41 --混沌石
ITEM_ID_SP_WARM2     = 42
ITEM_ID_SP_FIGHT4     = 47
ITEM_ID_SP_WARM3     = 48
ITEM_ID_SP_WARM4     = 49
ITEM_ID_SP_FIRSTYEAR     = 52
ITEM_ID_SP_FIGHT5     = 57
ITEM_ID_SP_WARM5     = 59
ITEM_ID_SP_FIGHT6     = 60
ITEM_ID_SP_LOVE     = 61
ITEM_ID_SP_FIGHT7     = 62
ITEM_ID_SP_RABBIT     = 63
ITEM_ID_SP_BEAR     = 64
ITEM_ID_SP_FIGHT8     = 65
ITEM_ID_SP_SUB      = 66
ITEM_ID_SP_HW      = 67
ITEM_ID_PUMPKIN      = 68
ITEM_ID_BELL         = 69
ITEM_ID_BUILD_STONE  = 72
ITEM_ID_SP_FIGHT9     = 70
ITEM_ID_SP_VPLI1     = 71
ITEM_ID_SP_MASK     = 88
ITEM_ID_SP_FIGHT10     = 89
ITEM_ID_SP_CHRISTMAS   = 93
ITEM_ID_SP_FIGHT11   = 102
ITEM_ID_MAGICGLIM  = 110
ITEM_ID_CHOCO      = 111
ITEM_ID_SP_NEWYEAR1   = 112
ITEM_ID_SP_FIGHT12   = 113
ITEM_ID_STONETABLET   = 124
ITEM_ID_STONEFIGURE   = 125
ITEM_ID_SP_FIGHT13   = 126
ITEM_ID_DARKREMAINS   = 131
ITEM_ID_SP_FIGHT14   = 138
ITEM_ID_SP_FIGHT15   = 140
ITEM_ID_ANNIVERSARY   = 142
ITEM_ID_SP_DEMON = 143
ITEM_ID_SP_FIGHT16   = 152
ITEM_ID_SP_FIGHT17   = 157
ITEM_ID_SP_FIGHT18   = 167
ITEM_ID_COLOR_CRYSTAL = 168
ITEM_ID_LIGHT_DARK_CRYSTAL = 169
ITEM_ID_GLORY = 170
ITEM_ID_ICECREAM = 173
ITEM_ID_SP_MOONCAKE = 175
ITEM_ID_SP_AFRICA1 = 178
ITEM_ID_SP_AFRICA2 = 179
ITEM_ID_SP_AFRICA3 = 180
ITEM_ID_FLOWERCAKE = 181
ITEM_ID_SP_HALLOMAS = 187
ITEM_ID_MAPLELEAF = 188
ITEM_ID_CHICKEN = 190
ITEM_ID_SP_THANK = 191
ITEM_ID_ABS_CRYSTAL = 194
ITEM_ID_CHRISTMAS_CARD = 196
ITEM_ID_SNOWFLAKE = 195
ITEM_ID_SP_CHRISTMAS2 = 197
ITEM_ID_SP_NEW_YEAR = 205
ITEM_ID_CANDY_FLOSS = 206
ITEM_ID_SP_CHINESE_NEW_YEAR = 215
ITEM_ID_RUDDER = 217
ITEM_ID_LUCKY_GRASS = 219
ITEM_ID_SP_FLOWER_CIRCLE = 220
ITEM_ID_MUSIC_BOX = 231

ITEM_ID_ICEBABY         = 26
ITEM_ID_HTASK_LOW       = 28
ITEM_ID_HTASK_HIGH      = 29
ITEM_ID_SPRINGBABY      = 43
ITEM_ID_FISHBABY        = 51
ITEM_ID_TINYSNOWMAN     = 92
ITEM_ID_GUILDFIRE       = 117
ITEM_ID_ELEMENT         = 165
ITEM_ID_CHIP         = 12002
ITEM_ID_ADVANCED_CHIP   = 58 
ITEM_ID_ENCHANT      = 10001
ITEM_ID_SMITH_CRYSTAL      = 10002
ITEM_ID_FORGE        = 10008
ITEM_ID_GACHA        = 12000
ITEM_ID_ARENA        = 12001
ITEM_ID_SUPERGACHA   = 12003
ITEM_ID_BROKEN       = 50
ITEM_ID_PIECE_Q4        = 40001 -- 绿色万能碎片
ITEM_ID_PIECE_Q5        = 40002 -- 红色万能碎片
ITEM_ID_PIECE_Q3        = 40003 -- 紫色万能碎片
ITEM_ID_PIECE_GROUP_Q5  = 40010 -- 红色有阵营万能碎片
ITEM_ID_PIECE_GROUP_Q4  = 40020 -- 绿色有阵营万能碎片
ITEM_ID_PIECE_GROUP_Q3  = 40030 -- 绿色有阵营万能碎片
ITEM_ID_EXQ_LIGHT_Q5 = 40046
ITEM_ID_EXQ_DARK_Q5 = 40045
ITEM_ID_EXQ_Q5 = 40039

ITEM_ID_PIECE_SKIN      = 60001 -- 皮肤万能碎片

-- 物品类型
ITEM_KIND_MONEY = 1
ITEM_KIND_EQUIP = 2
ITEM_KIND_ITEM  = 3
ITEM_KIND_GIFT  = 4
ITEM_KIND_HERO_PIECE   = 5
ITEM_KIND_SCROLL_PIECE = 6
ITEM_KIND_TREASURE_PIECE = 7
ITEM_KIND_SKIN_PIECE = 9

-- 万能碎片图标id
ICON_ID_HERO_Q6     = 10041
ICON_ID_HERO_Q5     = 10011
ICON_ID_HERO_Q4     = 10021
ICON_ID_HERO_Q3     = 10031
ICON_ID_HERO_EXQ_Q5 = 10042
ICON_ID_HERO_EXQ_LIGHT_AND_DARK_Q5 = 10043

-- 特殊英雄id
HERO_ID_ANY_Q3   = 3333
HERO_ID_ANY_Q4   = 4444
HERO_ID_ANY_Q5   = 5555
HERO_ID_ANY_Q6   = 6666
HERO_ID_GROUP_Q3 = 3099
HERO_ID_GROUP_Q4 = 4099
HERO_ID_GROUP_Q5 = 5099
HERO_ID_GROUP_Q6 = 6099
HERO_ID_SKIN     = 6001
HERO_ID_EXQ_LIGHT_Q5 = 7099
HERO_ID_EXQ_DARK_Q5 = 8099
HERO_ID_EXQ_Q5 = 9099

-- 所有的buff names
BUFF_ATK = "atk"
BUFF_HP = "hp"
BUFF_ARM = "arm"
BUFF_SPD = "spd"
BUFF_ENERGY = "energy"
BUFF_HIT = "hit"
BUFF_MISS = "miss"
BUFF_CRIT = "crit"
BUFF_TRUE_ATK = "trueAtk"
BUFF_BRK = "brk"
BUFF_STUN = "stun"
BUFF_ICE = "ice"
BUFF_STONE = "stone"
BUFF_FORBID = "forbid"
BUFF_REVIVE = "revive"
BUFF_CRIT_TIME = "critTime"
BUFF_FREE = "free"
BUFF_SKL_P = "sklP"
BUFF_DEC_DMG = "decDmg"
BUFF_HURT = "hurt"
BUFF_DOT = "dot"
BUFF_HEAL = "heal"
BUFF_HOT = "hot"
BUFF_HEAL_P = "healP"
BUFF_TRUE_HURT = "trueHurt"
BUFF_SIPHON_ATK = "siphonAtk"
BUFF_SIPHON_HP = "siphonHp"
BUFF_SIPHON_ARM = "siphonArm"
BUFF_SHIELD = "shield"
BUFF_BRIER = "brier"
BUFF_DOT_FIRE = "dotFire"
BUFF_DOT_POISON = "dotPoison"
BUFF_DOT_BLOOD = "dotBlood"
BUFF_DOT_SHADOWF = "shadowF"
BUFF_DOT_THU = "dotThu"
BUFF_DOT_BLAST = "dotBlast"
BUFF_ATK_P = "atkP"
BUFF_HP_P = "hpP"
BUFF_ARM_P = "armP"
BUFF_CHANGE_COMBAT = "changeCombat"
BUFF_ADD_HURT = "addHurt"
BUFF_RIMPRESS = "rImpress"
BUFF_CIMPRESS = "cImpress"
BUFF_FIMPRESS = "fImpress"
BUFF_OIMPRESS = "oImpress"
BUFF_KIMPRESS = "kImpress"
BUFF_SIMPRESS = "sImpress"
BUFF_WEAK = "weak"
BUFF_FEAR = "fear"
BUFF_HPBELOW_FEAR = "hpBelowFear"
BUFF_BALANCE = "balance"
BUFF_ATK_TRUEHURT = "atkTrueHurt"
BUFF_CUREPRESS = "curepress"
BUFF_SEEDPRESS = "seedpress"
BUFF_WIND = "wind"

-- 成就类型
ACHIEVE_TYPE_PLAYER_LV               = 1   
ACHIEVE_TYPE_VIP_LV                  = 2   
ACHIEVE_TYPE_GET_HERO_STAR4          = 3   
ACHIEVE_TYPE_GET_HERO_STAR5          = 4    
ACHIEVE_TYPE_GET_HERO_STAR6          = 5    
ACHIEVE_TYPE_DECOMPOSE_HERO          = 6   
ACHIEVE_TYPE_GET_EQUIP_GREEN         = 7   
ACHIEVE_TYPE_GET_EQUIP_RED           = 8   
ACHIEVE_TYPE_GET_EQUIP_ORANGE        = 9   
ACHIEVE_TYPE_DECOMPOSE_EQUIP         = 10  
ACHIEVE_TYPE_ARENA_ATTACK            = 11  
ACHIEVE_TYPE_ARENA_SCORE             = 12  
ACHIEVE_TYPE_PASS_FORT               = 13  
ACHIEVE_TYPE_COMPLETE_HEROTASK4      = 14  
ACHIEVE_TYPE_COMPLETE_HEROTASK5      = 15  
ACHIEVE_TYPE_COMPLETE_HEROTASK6      = 16  
ACHIEVE_TYPE_FRDBOSS                 = 17
ACHIEVE_TYPE_BRAVE                   = 18
ACHIEVE_TYPE_CASINO                  = 19
ACHIEVE_TYPE_SPESUMMON               = 20
ACHIEVE_TYPE_WAKE9                   = 21
ACHIEVE_TYPE_WAKE10                  = 22
ACHIEVE_TYPE_REGISTER                = 23
ACHIEVE_TYPE_HIGHSUMMON              = 24
ACHIEVE_TYPE_LOVESUMMONFIVE          = 25
ACHIEVE_TYPE_COMMONSUMMONFIVE        = 26
ACHIEVE_TYPE_SOLOPASS                = 27

TRIAL_FIGHT_CD = 300
TRIAL_SWEEP_CD = 22 * 60 * 60
TRIAL_SWEEP_OPEN_STAGE = 10

-- 开放功能所需等级
UNLOCK_TRAIN_LEVEL                    = 7
UNLOCK_SMITH_LEVEL                    = 12
UNLOCK_MIDAS_LEVEL                    = 13
UNLOCK_BLACKMARKET_LEVEL              = 10
UNLOCK_CASINO_LEVEL                   = 14
UNLOCK_ADVANCED_CASINO_LEVEL          = 80
UNLOCK_TASK_LEVEL                     = 17
UNLOCK_ARENA_LEVEL                    = 18
UNLOCK_CHALLENGE_LEVEL                = 20
UNLOCK_GUILD_LEVEL                    = 21
UNLOCK_TRIAL_LEVEL                    = 24
UNLOCK_TAVERN_LEVEL                   = 28
UNLOCK_GTREE_LEVEL                    = 25
UNLOCK_HERO_BRAVE                     = 40
UNLOCK_ARENA_3v3_LEVEL                = 55
UNLOCK_ARENA_FRIEND_LEVEL             = 60
UNLOCK_PET  						  = 70
UNLOCK_ACT_BROKEN  					  = 50
UNLOCK_SOLO_LEVEL					  = 72

UNLOCK_FIGHT_SPEED_LEVEL              = 50
UNLOCK_FIGHT_SKIP_LEVEL               = 70

UNLOCK_HERO_CRYSTAL                   = 40
UNLOCK_AIRISLAND_LEVEL                = 30

-- 触发评论的等级
REMARK_LEVEL                          = 33

-- 出战位置解锁
UNLOCK_BATTLE_POSITION1 = 5
UNLOCK_BATTLE_POSITION2 = 13

-- 首充礼包状态
FIRST_PAYMENT_REWARD_NO_PAY    = 0
FIRST_PAYMENT_REWARD_UNCLAIMED = 1
FIRST_PAYMENT_REWARD_CLAIMED   = 2

-- 英雄任务品质
HERO_TASK_QUALITY_BLUE = 1
HERO_TASK_QUALITY_YELLOW = 2
HERO_TASK_QUALITY_PURPLE = 3
HERO_TASK_QUALITY_GREEN = 4
HERO_TASK_QUALITY_RED = 5

COINS_CREATE_GUILD      = 100000
GEMS_CREATE_GUILD       = 40

-- 公会科技ID
GUILD_TECH_ID_MIDAS = 5

-- 竞技场类型
ARENA_TYPE_COMMON = 1
ARENA_TYPE_TIMELIMIT_ONE = 2
ARENA_TYPE_SINGLE_3V3 = 3

-- 竞技场地图
MAP_ID_ARENA = 7

--宝物解锁等级
UNLOCK_HERO_TREASURE = 1
--宝物装备的位置
EQUIP_POS_TREASURE = 6
--皮肤的位置
EQUIP_POS_SKIN = 7

--支付方式
PAY_METHOD = {
    ALI = 1,   --支付宝
    WX = 2,    --微信
}
