local faq = {}
faq[1] = {
    ["title"] = "Sıkça Karşılaşılan Oyun Sorunları",
    ["describe"] = "1.Soru: Cihazı değiştirdikten sonra, oyunu oynamaya nasıl devam edebilirim?|Cevap: Oyunu indirip giriş yaptıktan sonra, giriş arayüzünün sağ üst köşesinde bulunan ikona tıklayıp hesap adınızı ve şifrenizi girdikten sonra oyuna giriş yapabilirsiniz.|2.Soru: Hesap adını unutursam tekrar geri alabilir miyim?|Cevap: Eğer hesap adınızı unutursanız hesabınızı yenileyip tekrar geri almanız mümkün değildir. Bu yüzden hesap adınızı ve şifrenizi kesinlikle unutmayınız.|3.Soru: Hesabım çalındı ve şifresi değiştirildi. Ne yapmalıyım?|Cevap: Hesabınızın şifresinin başkası tarafından değiştirildiğini tespit etmeniz halinde anında müşteri hizmetleriyle iletişim kurunuz.|4.Soru: Bağlantı zaman aşımına uğradı ve giriş yapamıyorum. Ne yapmalıyım?|Cevap: Eğer oyuna giriş yapamıyor iseniz, lütfen yeniden bağlanmayı deneyin ya da oyunu kapatıp yeniden açın.|5.Soru: Oyun sürekli güncelleme konumunda (check updates) ve giriş yapamıyorum. Ne yapmalıyım?|Cevap: Böyle bir durumda oyunu kapatıp tekrar açmayı ya da bağlantı ayarlarını kontrol edip tekrar bağlanmayı deneyin. Sorunun devam etmesi halind lütfen müşteri hizmetleri ile iletişim kurunuz.|6.Soru: Veri ya da hesap bilgileri kaybolduğu zaman ne yapmalıyım?|Cevap: Böyle bir durumla karşılaştığınızda, öncelikle doğru sunucudan giriş yapıp yapmadığınızı kontrol edin. Çünkü farklı sunucular arasında veri paylaşımı yapılmaz. Sunucunun doğru olması halinde sorun hala devam ediyorsa oyun ID kimliği, kayıt olduğunuz e-mail adresi bilgilerini tedarik ederek müşteri hizmetleriyle iletişim kurunuz.|7.Soru: Oyun sırasında sürekli oyundan düşüyorum. Ne yapmalıyım?|Cevap: Öncelikle cihazınızın bağlantı durumunu kontrol edip yeniden deneyin. Sorun devam ediyorsa müşteri hizmetleriyle iletişime geçin.|8.Soru: Oyun hata verip kapandığı zaman ne yapmalıyım?|Cevap: Oyun bu şekilde bir hata verdiği zaman oyuna tekrar giriş yapmayı deneyin. Sorun hala devam ediyorsa cihazı yeniden başlatın ya da cihazın model bilgilerini müşteri hizmetleri personeline bildirerek sorunu çözmeye çalışın.|9.Soru: Hile yapan bir oyuncu ile karşılaştığımda ne yapmalıyım?|Cevap: Oyuncularımız için her zaman eşit bir oyun ortamı oluşturmaya çalıştığımızdan dolayı, oyuncuların oyun BUG açıklarından yararlanarak hile yapmasına asla müsaade edilmemektedir. Eğer böyle bir durumla karşılaşmanız durumunda lütfen anında geri bildirim oluşturup müşteri hizmetlerine bildiriniz. Gereken en kısa zamanda yapılacaktır.",
}
faq[2] = {
    ["title"] = "Sıkça Karşılaşılan Sosyal Platform Sorunları",
    ["describe"] = "1.Soru: Sohbet kanalı üzerinde başka oyunculardan gelen mesajları nasıl engellerim?|Cevap: Sohbet kanalı üzerinde engellemek istediğiniz oyuncunun resmi üzerine gelip engelleme butonuna tıklayarak mevcut oyuncunun size mesaj göndermesini önlemiş olursunuz.|2.Soru: Sohbet kanalına reklam ve dolandırıcı mesajlar gönderen oyuncu ile karşılaştığımda ne yapmalıyım?|Cevap: Ana arayüzün sol tarafındaki geri bildirim üzerinden müşteri hizmetleri ile iletişim kurarak kuralları ihlal eden oyuncunun hesap ID kimlik bilgisini bildirerek, mümkün olması halinde ekran resminin ekran olarak göndermeniz gerekmektedir.|3.Soru: Oyun sırasında nasıl arkadaş eklenir?|Cevap: Sohbet kanalı üzerinde oyuncunun remine tıklayarak arkadaşlık isteği gönderebilirsiniz. Ayrıca başvuru sırasında oyuncu id kimlik bilgisi ya da arkadaş tavsiye başvurusu gönderebilirsiniz.|4.Soru: Arkadaşlar arasında nasıl bir interaktif bağlantı sağlanabilir?|Cevap: Arkadaşlar interaktif bağlantı ile birleşip BOSS birimine saldırabilirler, birbirlerine kalp göndererek Kalp Çağırma işlemi gerçekleştirilebilir. Ayrıca arkadaşlara mesaj gönderilerek iletişim sağlanabilir.|5.Soru: Birliğe nasıl katılabilirim?|Cevap: Ana arayüz üzerinde bulunan Birlik butonuna tıklanarak tavsiye edilen birlik seçilerek ya da belirli bir birlik ID kimliği girilerek katılım başvurusu gerçekleştirilebilir. Ayrıca kendinize ait olan birliğe başka oyuncuların katılması için davet gönderebilirsiniz.|6.Soru: Birliğe katıldıktan sonra hangi oyun türleri oynanabilir?|Cevap: Birliğe katıldıktan sonra yoklama yaparak bilrik seviyesini geliştirebilir ve Birlik Parası kazanabilirsiniz. Ayrıca Değirmen ve Birlik Ek Sahnesi üzerinden belirli miktarda Birlik Parası kazanabilirsiniz. Her hafta 1 defa düzenlenen Birlik Savaşı'na kayıt yaptırarak da büyük miktarda Birlik Parası ve diğer ödüllerden elde edebilirsiniz.|7.Soru: Birliği değiştirirsem ne gibi etkileri olur?|Cevap: Bu haftaki Birlik Savaşı'na kayıt yaptırmış iseniz, birliğinizi değiştirmeniz halinde Birlik Savaşı'na katılamazsınız. Dolayısıyla savaştan elde edilecek herhangi bir ödül kazanamazsınız.|8.Soru: Birlik Parası nerede kullanılır?|Cevap: Birlik Parası, Birlik içerisinde yer alan Birlik Marketi üzerinden eşya satın almak için kullanılmaktadır. Birlik Parası tüketerek Birlik Teknolojisi üzerinden Birlik Becerinizi geliştirebilirsiniz.|9.Soru: Birlik Teknolojisi üzerinden beceri geliştirmek ne işe yarar?|Cevap: Birlik Teknoloijsi içerisinde bulunan 5 farklı meslek becerisi kendinize ait olan kahramanların özelliklerini geliştirir.",
}
faq[3] = {
    ["title"] = "Sıkça Karşılaşılan Ödeme Sorunları",
    ["describe"] = "1.Soru: Nasıl VIP oyuncusu olunur?|Cevap: Belirli miktarda Elmas satın aldıktan sonra anında VIP oyuncu olunabilmektedir. Ne kadar fazla Elmas satın alırsanız VIP seviyeniz o kadar yüksek olmaktadır.|2.Soru: İlk ödeme yapıldığında ne tür ödüller vardır?|Cevap: İlk ödemede anında çift kat elmas kazanılır, her seviyede sadece 1 defa yapılabilir. Özel eşyalardan (Örnek: Aylık Kart) içermez.|3.Soru: Ödeme yapıp satın aldığım eşyamın tarafıma ulaşmaması durumunda ne yapmam gerekiyor?|Cevap: Böyle bir durumla karşılaşmanız halinde lütfen öncelikle oyunu yeniden başlatmayı deneyin. Sorun devam ediyorsa lütfen müşteri hizmetleriyle iletişim kurun.|4.Soru: Yapılan ödemenin başarılı olduktan sonra düşen bakiye neden değişiyor?|Cevap: Ödemeden düşen miktarı mevcut bulunduğunuz ülkenin anlık kuruna göre belirlemektedir. Bu yüzden anlık kur değişimine göre kesilen miktarlar da değişebilmektedir.",
}
faq[4] = {
    ["title"] = "İletişim",
    ["describe"] = "Oyunla ilgili bir sorunla karşılaştığınızda ya da belirtmek istediğiniz bir fikriniz var ise, geri bildirim sayfası üzerinden tarafımıza e-mail gönderebilirsiniz. E-mail adresimiz: idleheroes.feedback@gmail.com.",
}
return faq