local faq = {}
faq[1] = {
    ["title"] = "Câu hỏi game thường gặp",
    ["describe"] = "1. Hỏi: sau khi đổi thiết bị, làm sao để tiếp tục game？|Đáp: sau khi tải và vào game, trong giao diện đăng nhập, nhấp nút hình người nhỏ ở góc trên bên phải để nhập tên tài khoản và mật mã của bạn là vào được game.|2. Hỏi: quên tài khoản có tìm lại được không？|Đáp: quên tài khoản sẽ không thể tìm lại, nên hãy ghi nhớ tên tài khoản và mật mã của bạn.|3.Hỏi: tài khoản bị hack, đổi mật mã thì phải làm sao？|Đáp: khi mật mã tài khoản của bạn bị đổi, hãy liên hệ với bộ phận hỗ trợ của chúng tôi.|4. Hỏi: khi lỗi mạng, không thể đăng nhập thì phải làm sao？|Đáp: nếu bạn không thể đăng nhập. Hãy thử liên kết lại, hoặc đóng rồi khởi động lại game.|5. Hỏi: khi game cứ cập nhật suốt (check updates) không thể vào thì phải làm sao？|Đáp: khi bạn vào game mà gặp trường hợp cập nhật suốt không thể vào game thì hãy thử đóng rồi khởi động lại game hoặc đổi mạng rồi thử lại, nếu vẫn không được thì hãy liên hệ với hệ thống hỗ trợ của chúng tôi.|6. Hỏi: khi dự liệu tài khoản bị mất thì phải làm sao？|Đáp: nếu gặp trường hợp mất dữ liệu, trước hết hãy kiểm tra xem bạn có đăng nhập đúng Server không, vì mỗi Server có dữ liệu khác nhau, nếu xác nhận đăng nhập đúng Server mà không có dữ liệu thì hãy liên hệ với chúng tôi, khi liên hệ hãy cung cấp ID Game, email đăng ký và các thông tin liên quan, chúng tôi sẽ cố gắng giải quyết.|7. Hỏi: game cứ bị đứt mạng khi chơi thì phải làm sao？|Đáp: nếu đang chơi game mà bị đứt mạng liên tục, bạn hãy kiểm tra trạng thái liên kết mạng của thiết bị, đồng thời kết nối lại mạng, nếu vẫn bị như vậy thì hãy liên hệ với hệ thống hỗ trợ của chúng tôi.|8. Hỏi: chơi game tự nhiên bị thoát ra thì phải làm sao？|Đáp: khi bạn tự nhiên bị thoát khỏi game, hãy đóng tất cả các ứng dụng ẩn của thiết bị rồi vào lại game, nếu vẫn bị tự động thoát thì hãy khởi động lại thiết bị hoặc liên hệ bộ phận hỗ trợ, cung cấp thông tin thiết bị đó của bạn.|9. Hỏi: phát hiện có người chơi ăn gian thì phải làm sao？|Đáp: chúng tôi nỗ lực tạo nên môi trường game công bằng, cấm tất cả người chơi lợi dụng BUG game để phá vỡ sự công bằng đó. Khi bạn phát hiện có người chơi ăn gian, hãy phàn hồi với chúng tôi, chúng tôi sẽ xử lý những người chơi ăn gian.",
}
faq[2] = {
    ["title"] = "Câu hỏi về tương tác thường gặp",
    ["describe"] = "1.Hỏi: làm thế nào để ẩn những người khác trên kênh chat？|Đáp: bạn có thể nhấp vào avatar người chơi trên kênh chat, sau đó nhấp nút ẩn để ẩn phát ngôn của người đó.|2. Hỏi: khi thấy có người gửi quảng cáo trên kênh chat hoặc gửi tin lừa đảo phải làm sao？|Đáp: bạn có thể nhấp vào giao diện bên trái để phản hồi với nhân viên hỗ trợ, đồng thời cung cấp thông tin ID của tài khoản người chơi đó, bạn cũng có thể cắt ảnh để làm bằng chứng, ID người đó rồi gửi tới hòm thư chúng tôi.|3. Hỏi: làm sao để thêm bạn trong game？|Đáp: bạn có thể nhấp avatar người chơi trên kênh chat rồi gửi yêu cầu, cũng có thể tới giao diện bạn bè nhập id người chơi hoặc gửi yêu cầu kết bạn với bạn bè đề cử.|4.Hỏi: bạn bè tương tác với nhau thế nào？|Đáp: bạn bè có thể giúp nhau đánh BOSS, cũng có thể tặng Trái Tim cho nhau để tiến hành triệu hồi trái tim, bạn còn có thể gửi thư để giao lưu với bạn bè mình.|5. Hỏi: làm thế nào để gia nhập Guild？|Đáp: bạn có thể nhấp nút Guild trong giao diện chính, chọn Guld đề cử rồi gửi yêu cầu hoặc nhấp ID Guild để tìm Guild rồi gửi yêu cầu, bạn cũng có thể tạo Guild và mời người khác gia nhập Guild của mình.|6. Hỏi: gia nhập Guild được tham gia những gì？|Đáp: sau khi gia nhập Guild, bạn có thể thông qua báo danh mà tăng Lv Guild đồng thời nhận được Xu Guild, cũng có thể nhận được số Xu Vàng nhất định trong Xưởng, phó bản Guild, còn có thể báo danh hoạt động Guld Chiến mỗi tuần 1 lần để dành được nhiều Xu Guild và các thưởng khác.|7. Hỏi: đổi Guild có ảnh hưởng gì？|Đáp: nếu bạn đã báo danh tham gia Guild Chiến tuần này, thì sau khi đổi Guild bạn sẽ không thể tham gia Guild Chiến tuần này, đồng thời không nhận được bất cứ thưởng nào trong Guild Chiến tuần này.|8. Hỏi: Xu Guild có tác dụng gì？|Đáp: Xu Guild dùng để mua đạo cụ trong Shop Guild trong Guild, cũng có thể dùng trong Khoa Kỹ Guild tăng cấp kỹ năng Guild của bạn.|9. Hỏi: tăng cấp kỹ năng trong Khoa Kỹ Guild có tác dụng gì？|Đáp: tăng cấp 5 kỹ năng nghề trong Khoa Kỹ Guild để giúp bản thân tăng năng lực Hero tương ứng mà bạn sở hữu.",
}
faq[3] = {
    ["title"] = "Câu hỏi về Nạp thường gặp",
    ["describe"] = "1. Hỏi: làm thể nào để trở thành người chơi VIP？|Đáp: khi bạn mua số lượng Kim Cương nhất định là được trở thành VIP, mua càng nhiều Kim Cương thì Lv VIP càng cao, đặc quyền cũng càng nhiều.|2. Hỏi: Nạp lần đầu có thưởng gì？|Đáp: Nạp lần đầu sẽ nhận được Kim Cương gấp đôi, mỗi mức Nạp chỉ được 1 lần. Không bao gồm thương phẩm đặc biệt (như Thẻ Tháng...).|3. Hỏi: khi Nạp rồi mà không nhận được đạo cụ thì phải xử lý thế nào？|Đáp: khi bản phát hiện đã Nạp thành công mà không nhận được đạo cụ, hãy thử khởi động lại game. Nếu thử mà vẫn không nhận được, hãy liên hệ với chúng tôi.|4. Hỏi: tại sao sau khi Nạp thành công thì số tiền trừ đi lại thay đổi？|Đáp: tiền trừ khi Nạp căn cứ vào loại tiền tệ Quốc Gia bạn đang ở, được dựa vào tỷ giá để đổi, vì vậy sẽ sẽ thay đội vì lý do tỷ giá.",
}
faq[4] = {
    ["title"] = "Liên hệ chúng tôi",
    ["describe"] = "Khi bạn gặp bất cứ vấn đề gì trong game hoặc có ý kiến gì, bạn có thể gửi thông tin tới chung tôi trong Phản Hồi, cũng có thể gửi thư cho chúng tôi. Hòm thư của chúng tôi là: idleheroes.feedback@gmail.com。",
}
return faq