local faq = {}
faq[1] = {
    ["title"] = "Questões gerais",
    ["describe"] = "1.Q: Acabei de alterar o meu dispositivo. Como faço para continuar o jogo?|A: 1. Faça o download do jogo no novo dispositivo 2.Toque o ícone pessoa no canto superior direito 3. Digite sua conta e senha.|2.Q: Esqueci minha conta. Como faço para recuperá-la?|A: É impossível recuperar a conta esquecida. Então, lembre-se de sua conta e senha.|3.Q: Minha conta foi roubada e a senha alterada. O que eu faço?|A: Se sua senha foi alterada, entre em contato com nosso serviço ao cliente imediatamente.|4.Q: Não consigo fazer login depois que a rede expirou. O que eu faço?|A: 1. Tente reconectar 2. Force fechar o jogo e reiniciá-lo.|5.Q: O jogo continua a verificar atualizações e não consigo entrar no jogo. O que eu faço?|A: 1. Force fechar o jogo e reiniciá-lo. 2. Se 1 não funcionar, conecte-se a outra rede e tente novamente. 3. Se 1 e 2 não resolverem o problema, entre em contato com nosso serviço ao cliente.|6.Q: O que devo fazer quando meus dados ou conta são perdidos?|A: 1. Verifique se você está no servidor correto. Os dados não são compartilhados entre servidores diferentes. 2. Se o servidor estiver correto, forneça seu ID e e-mail registrado para nosso serviço ao cliente. Nós o ajudaremos o mais rápido possível.|7.Q: Eu continuo caindo do jogo. O que eu faço?|A: 1. Verifique sua conexão de rede. 2. Experimente novas conexões. 3. Se 1 e 2 não funcionarem, entre em contato com nosso serviço ao cliente.|8.Q: O jogo caiu. O que eu faço?|A: 1. Force fechar o jogo e reiniciá-lo 2. Experimente o método 1 várias vezes 3. Se 1 e 2 não funcionar, forneça o tipo de dispositivo ao serviço de atendimento ao cliente e nós o ajudaremos o mais rápido possível.|9.Q: Eu encontrei alguns trapaceiros. O que eu faço?|A: Ambiente justo e bom equilíbrio são o que mais nos preocupam. Quando você encontrar trapaceiros no jogo, denuncie-os para nós e vamos lidar com eles o mais rápido possível.",
}
faq[2] = {
    ["title"] = "Questões sociais gerais",
    ["describe"] = "1.Q: Alguns jogadores enviam spam no bate-papo. O que eu faço?|A: 1. Clique com o botão direito no avatar de um jogador no chat. 2. Clique em 'Bloquear' para bloquear o jogador.|2.Q: Alguns jogadores estão postando propagandas ou informações de fraude no bate-papo. O que eu faço?|A: 1. Toque em 'Experiência' no lado esquerdo da página principal. 2. Informe o ID do jogador para o nosso serviço ao cliente 3. Você também pode denunciar um jogador fornecendo uma captura de tela e ID do jogador por e-mail.|3.Q: Como faço para adicionar amigos no jogo?|A: 1. Toque no avatar do jogador no chat para enviar a solicitação. 2. Digite o ID do jogador na página de amigos. 3. Envie solicitações aos jogadores recomendados.|4.Q: Como faço para interagir com amigos?|A: 1. Os amigos podem ajudar-se mutuamente na derrota dos chefes. 2. Os amigos podem enviar corações uns aos outros. Corações podem ser usados em Invocação de Coração. 3. Você pode se comunicar com amigos através de Correspondência.|5.Q: Como faço para entrar em uma corporação?|A: 1. Toque no ícone da corporação na página principal 2. Escolha uma corporação recomendada ou procure uma com a ID da corporação 3. Crie sua própria corporação e convide outros jogadores.|6.Q: O que posso fazer quando numa corporação?|A: 1. Entre diariamente para subir de nível na corporação e ganhar moedas da corporação 2. Obter moedas e ouro dos Moinho de vento e Masmorra 3. Inscreva-se para a Guerra da Corporação semanal por uma chance de ganhar moedas da corporação e outras recompensas.|7.Q: O que acontecerá quando eu mudar de corporação?|A: Se você se inscreveu para participar da guerra da corporação, não pode participar da Guerra da semana ou obter recompensas da guerra da corporação se mudar de corporações.|8.Q: Para que servem as moedas da corporação?|A: As moedas da corporação podem ser usadas para comprar itens na loja da corporação e atualizar as habilidades da corporação através da Tecnologia da Corporação.|9.Q: O que posso ganhar com a atualização das Tecnologias da Corporação?|A: A atualização de habilidades de 5 classes na Tecnologia aumenta as estatísticas dos heróis correspondentes.",
}
faq[3] = {
    ["title"] = "Perguntas Gerais de Pagamento",
    ["describe"] = "1.Q: Como faço para me tornar um jogador VIP?|A: Você pode se tornar um VIP depois de comprar o número necessário de diamantes. Quanto mais diamantes comprados, maior o nível VIP e mais privilégios.|2.Q: O que posso obter com o 1 Top-up?|A: O primeiro top-up concede diamantes duplos. Cada nível está disponível apenas uma vez. Ofertas especiais (como o cartão mensal) não estão incluídas.|3.Q: Eu paguei por itens, mas não os recebi durante o carregamento, o que devo fazer?|A: 1. Reinicie o jogo e verifique a sua conta 2. Repetir 1 3. Entre em contato com nosso serviço ao cliente.|4.Q: O que eu pago não é o mesmo que o que recebo. Por quê?|A: O pagamento varia de acordo com a variação da taxa de câmbio.",
}
faq[4] = {
    ["title"] = "Contate-Nos",
    ["describe"] = "Se você tiver quaisquer problemas ou sugestões, entre em contato conosco através de Suporte ou por e-mail. Nosso endereço de e-mail é: idleheroes.feedback@gmail.com.",
}
return faq