local faq = {}
faq[1] = {
    ["title"] = "Questions Générales",
    ["describe"] = "1.Q: Je viens de changer d'appareil. Comment puis-je continuer le jeu?|A: 1. Téléchargez le jeu sur le nouvel appareil. Cliquez sur l'icône en forme d'humain dans le coin supérieur droit 3. Rentrez votre nom de compte et votre mot de passe.|2.Q: J'ai oublié mon nom de compte. Comment le retrouver?|A: Il est impossible de retrouver les noms et mot de passes d'un compte. Veuillez bien vous en souvenir. |3.Q: Mon compte a été volé et le mot de passe a été modifié. Que faire? |A: Si votre mot de passe a été modifié, veuillez immédiatement contacter notre service client. |4.Q: Je ne peux me connecter après un timeout réseau. Que faire? |A: 1. Essayez de vous reconnecter 2. Forcez le jeux à fermer et redémarrez. |5.Q: Le jeu recherche continuellement des mises à jours et je ne peut commencer à jouer. Que faire? |A: 1. Forcez le jeu à fermer et redémarrez. 2. Si la solution 1 ne marche pas, connectez vous à un autre réseau et réessayez. 3. Si 1 et 2 ne résoud pas votre problème , veuillez contacter notre service client. |6.Q: Que faire si mes données ou compte du jeu sont perdus?|A: 1. Assurez vous d'être sur le serveur approprié. Les données ne sont pas partagées entre les serveurs. 2. Si vous êtes sur le bon serveur , veuillez faire parvenir votre nom d'utilisateur et votre courriel à notre service client. On vous aidera au plus vite.|7.Q: Je me retrouve continuellement  hors-ligne. Que faire? |A: 1. Vérifiez votre connexion réseau. 2. Essayez de nouvelles connexions. 3. Si 1 et 2 ne résoud pas votre problème , veuillez contactez notre service client. |8.Q: Le jeu plante. Que faire? |A: 1. Forcez le jeu à fermer et redémarrez. 2. Essayez la méthode 1 plusieurs fois 3. Si 1 et 2 de fonctionnent pas, veuillez faire parvenir votre modèle d'appareil au service client et nous vous aiderons au plus vite. |9.Q: J'ai découvert quelques tricheurs. Que faire? |A: Un environnement équitable et une bon équilibre sont ce qui nous est de plus cher. Si vous découvrez des tricheurs, veuillez nous le signaler et nous nous occuperons d'eux au plus vite.",
}
faq[2] = {
    ["title"] = "Questions Sociales Générales",
    ["describe"] = "1.Q: Certains joueurs polluent le chat. Que faire?|A: 1. Cliquez avec le bouton droit sur l'avatar du joueur dans le chat. 2. Cliquez 'Bloquer' pour bloquer le joueur.|2.Q: Certains joueurs postent des pubs ou des info Frauduleuses dans le chat. Que faire? |A: 1. Cliquez sur 'commentaires' à gauche dans la page d'accueil. 2. Dénoncez le nom d'utilisateur du joueur à notre service client 3. Vous pouvez aussi dénoncer un joueur en faisant parvenir une capture d'écran et le nom d'utilisateur du joueur par courriel. |3.Q: Comment ajouter des amis dans le jeux? |A: 1. Cliquez sur l'avatar du joueur dans le chat et envoyez une demande. 2 Saisissez le nom d'utilisateur du joueur dans la page ami. 3. Envoyez une demande aux joueurs recommandés.|4.Q: Comment communiquer avec des amis?|A: 1. Les amis peuvent s'entraider pour vaincre les boss. 2. Les amis peuvent s'envoyer des cœurs. Les cœurs peuvent être utilisés dans les Invocations Cœurs 3. Vous pouvez communiquer avec vos amis via les Courriels.|5.Q: Comment rejoindre une guilde?|A: 1. Cliquez sur la guilde dans la page d'accueil 2. Choisissez une guilde recommandée ou faites une recherches avec le nom de la guilde 3. Créez votre guilde et invitez des joueurs à vous rejoindre.|6.Q: Qu'est-ce que je peux faire dès que je suis dans une guilde?|A: 1. Connectez vous quotidiennement pour faire monter la guilde en niveau et gagnez des pièces guildes 2. Gagnez des pièces guildes et de l'or du Moulin et du Donjon de la Guilde 3. Inscrivez vous aux Guerres de Guildes hebdomadaires pour une chance d'avoir des pièces guildes et d'autres récompenses. |7.Q: Qu'adviendra t-il quand je change de guilde? |A: Si vous vous êtes inscrit pour une guerre de guildes , vous ne pouvez vous réinscrire à la Guerre de Guilde de cette semaine. Vous n'aurez pas non plus droit aux récompenses de Guerre de Guildes si vous changez de guilde. |8.Q: Que faire des pièces guildes? |A: Le pièces guildes peuvent être utilisées pour acheter des objets dans la boutique de guilde et sert à améliorer les talents des guildes via Guilde Tech.|9.Q: Comment puis-je bénéficier des améliorations Guilde Tech?|A: Améliorez les talents des 5 catégories dans Guilde Tech et cela augmentera les attributs des héros correspondants.",
}
faq[3] = {
    ["title"] = "Questions Générales sur les Paiements",
    ["describe"] = "1.Q: Comment devenir un joueur VIP?|A: Vous pouvez devenir un joueur VIP après avoir acheté le nombre requis de diamants. Plus vous achetez des diamants, plus haut sera votre niveau VIP et plus grands seront les privilèges.|2.Q: Quel sont les bénéfices de la première recharge? |A: La première recharge vous octroie le double des diamants. |3.Q: J'ai payé pour certains objets mais je ne les ai pas reçu pendant le chargement du jeu. Que faire? |A: 1. Redémarrez le jeu et vérifiez votre compte 2. Réessayez 1 3. Contactez le service client à temps.|4.Q: Je n'ai pas été facturé de ce que j'ai payé. Pourquoi? |A: Le paiement peut varier en fonction du taux de change.",
}
faq[4] = {
    ["title"] = "Contactez Nous",
    ["describe"] = "Si vous avez des problèmes et des suggestions , veuillez nous contactez via Aide ou courriel .Notre adresse mail est : idleheroes.feedback@gmail.com",
}
return faq