
-- 0 - disable debug info, 1 - less debug info, 2 - verbose debug info
DEBUG = 0
DEBUG_FPS = false
DEBUG_MEM = false

---- design resolution
--CONFIG_SCREEN_WIDTH  = 640
--CONFIG_SCREEN_HEIGHT = 960

---- auto scale mode
--CONFIG_SCREEN_AUTOSCALE = "FIXED_WIDTH"

CONFIG_PROTOCOL_HEADER_FIRST_FIELD_LEN = 2
CONFIG_PROTOCOL_HEADER_EXCEPT_FIRST_LEN = 4
CONFIG_PROTOCOL_HEADER_EXCEPT_FIRST_LEN_RECV = 2
CONFIG_PROTOCOL_HEADER_LEN = CONFIG_PROTOCOL_HEADER_FIRST_FIELD_LEN + CONFIG_PROTOCOL_HEADER_EXCEPT_FIRST_LEN
CONFIG_PROTOCOL_HEADER_LEN_RECV = CONFIG_PROTOCOL_HEADER_FIRST_FIELD_LEN + CONFIG_PROTOCOL_HEADER_EXCEPT_FIRST_LEN_RECV



