local faq = {}
faq[1] = {
    ["title"] = "Preguntas Generales",
    ["describe"] = "1.Q: Acabo de cambiar mi dispositivo. ¿Cómo puedo continuar el juego?|A: 1. Descargue el juego en el nuevo dispositivo 2.Toque el icono humano en la esquina superior derecha 3. Ingrese su cuenta y contraseña.|2.Q: He olvidado mi cuenta. ¿Cómo la recupero?|A: Es imposible recuperar la cuenta olvidada. Por favor, recuerde su cuenta y contraseña.|3.Q: Mi cuenta ha sido robada y han cambiado la contraseña. ¿Qué debo hacer?|A: Si su contraseña ha sido cambiada, póngase en contacto con nuestro servicio de atención al cliente inmediatamente.|4.Q: No puedo iniciar sesión después de que la red ha expirado. ¿Qué debo hacer?|A: 1. Intente volver a conectarse 2. Cerrar el juego y reiniciarlo.|5.Q: El juego sigue buscando actualizaciones y no puedo entrar en el juego. ¿Qué debo hacer?|A: 1. Cierre el juego y reinícielo. 2. Si 1 no funciona, conéctese a otra red e inténtelo de nuevo. 3. Si 1 y 2 no resuelven su problema, comuníquese con nuestro servicio de atención al cliente.|6.Q: ¿Qué debo hacer cuando se pierden mis datos o mi cuenta?|A: 1. Asegúrese de que está en el servidor correcto. Los datos no se comparten entre diferentes servidores. 2. Si el servidor es correcto, proporcione su ID y correo electrónico registrado a nuestro servicio de atención al cliente. Le ayudaremos lo antes posible.|7.Q: Sigo siendo expulsado fuera de línea. ¿Qué debo hacer?|A: 1. Compruebe su conexión de red 2. Pruebe nuevas conexiones 3. Si 1 y 2 no funcionan, póngase en contacto con nuestro servicio de atención al cliente.|8.Q: El juego colapso. ¿Qué debo hacer?|A: 1. Cierre el juego y reinícielo. 2. Pruebe el método 1 varias veces 3. Si 1 y 2 no funcionan, proporcione su tipo de dispositivo al servicio de atención al cliente y le ayudaremos lo antes posible.|9.Q: He encontrado algunos tramposos. ¿Qué debo hacer?|A: Lo que más nos importa son un ambiente justo y buen equilibrio. Cuando encuentres tramposos en el juego, reportalo con nosotros y nos encargaremos lo antes posible.",
}
faq[2] = {
    ["title"] = "Preguntas Generales Sociales",
    ["describe"] = "1.Q: Algunos jugadores están haciendo spam en el chat. ¿Qué debo hacer?|A: 1. Haga clic derecho en el avatar de un jugador en el chat 2. Haga clic en 'Bloquear' para bloquear al jugador.|2.Q: Algunos jugadores publican información de Anuncios o Fraude en el chat. ¿Qué debo hacer?|A: 1. Toque en 'Retroalimentación' a la izquierda de la página principal. 2. Reporte el ID del jugador a nuestro servicio de atención al cliente. 3. También puede reportar a un jugador proporcionando una captura de pantalla e identificación del jugador a través del correo electrónico.|3.Q: ¿Cómo puedo agregar amigos en el juego?|A: 1. Toque el avatar del jugador en el chat para enviar la solicitud. 2. Ingrese el ID del jugador en la página de amigos. 3. Enviar solicitudes a los jugadores recomendados.|4.Q: ¿Cómo interactúo con amigos?|A: 1. Los amigos pueden ayudarse mutuamente en la derrota de los jefes. 2. Los amigos pueden enviar corazones el uno al otro. Los corazones se pueden utilizar en Convocaciones de corazones 3. Usted puede comunicarse con amigos a través del correo.|5.Q: ¿Cómo me uno a un gremio?|A: 1. Toque el icono del gremio en la página principal 2. Elija un gremio recomendado o busque uno con el ID del gremio 3. Crear su propio gremio e invite a otros jugadores.|6.Q: ¿Qué puedo hacer cuando estoy en un gremio?|A: 1. Ingrese diariamente para subir de nivel el gremio y gane monedas de gremio 2. Obtenga monedas de gremio y oro del Molino de Viento y el Calabozo del Gremio 3. Inscríbase en la guerra semanal del gremio para tener la oportunidad de ganar monedas de gremio y otras recompensas.|7.Q: ¿Qué pasará cuando cambie de gremio?|A: Si ha solicitado inscribirse en la guerra del gremio, no puedes unirte a la Guerra del Gremio de la semana ni recibir recompensas de la guerra del gremio si cambias de gremio.|8.Q: ¿Para qué sirven las monedas del gremio?|A: Las monedas del gremio se pueden utilizar para comprar artículos en la tienda del gremio y mejorar las habilidades del gremio a través de la Tecnología del Gremio.|9.Q: ¿Qué puedo ganar al actualizar la Tecnología del Gremio?|A: Actualizar las habilidades de 5 clases en la Tecnología del Gremio aumenta las estadísticas de héroes.",
}
faq[3] = {
    ["title"] = "Preguntas Generales de Pago",
    ["describe"] = "1.Q: ¿Cómo puedo convertirme en un jugador VIP?|A: Usted puede convertirse en VIP después de comprar el número requerido de diamantes. Entre más diamantes comprados, mayor será el nivel VIP y tendrá más privilegios.|2.Q: ¿Qué puedo obtener de la primera Recarga?|A: La primer recarga otorga diamantes dobles. Cada nivel está disponible una sola vez. Las ofertas especiales (como la tarjeta mensual) no están incluidas.|3.Q: He pagado por artículos pero no los recibí durante la recarga, ¿qué debo hacer?|A: 1. Reinicie el juego y compruebe su cuenta. 2. Repita el paso 1. 3. Póngase en contacto con nuestro servicio de atención al cliente.|4.Q: Lo que pagué no es lo mismo que lo que me cobran. ¿Por qué?|A: El pago cambia según la variación del tipo de cambio.",
}
faq[4] = {
    ["title"] = "Contáctenos",
    ["describe"] = "Si tiene algún problema o sugerencia, póngase en contacto con nosotros a través de Soporte o por correo. Nuestra dirección de correo electrónico es: idleheroes.feedback@gmail.com.",
}
return faq